### ISSUE TITLE
NTR: [current term label] New sample-collected-by sequencing centre

### ISSUE THREAD

**Issue by GLTOhorsman** [cidgoh/CanCOGeN_Contextual_Data_Specification#1]
### Proposed Term Label

St. Joseph’s Healthcare Hamilton

### Proposed Associated Field(s)

sample collected by

### Definition/Description

St. Joseph's Healthcare Hamilton is a 777-bed research hospital and academic health science centre located in Hamilton, Ontario, that is affiliated with the Michael G. DeGroote School of Medicine of McMaster University as well as Mohawk College.

### Definition Source

https://en.wikipedia.org/wiki/St._Joseph%27s_Healthcare_Hamilton

### Guidance

Use this term when indicating COVID-19 samples extracted and sequenced at St. Joseph’s Healthcare Hamilton and submitted by the Ontario COVID-19 Genomic Network

### Additional Comments (not an annotation)

This is one of three requests put forward by the Ontario COVID-19 Genomic Network in coordination with the National Microbiology Laboratory to facilitate data sharing. It will require both a term in dataharmonizer, and an export tolerance such that this term is accepted in the "NML LIMS" export. Please consult with user https://github.com/GH-Emily for timing of release to align with the matching changes they require on the NML side.

### Optional - Contributor Attribution

https://orcid.org/0000-0002-8117-5050

**Comment by GH-Emily** [comment]
NMLB-COG is okay with a **beta release** of this standard, but is currently unable to intake data with these new values.

**Comment by KirstenPalmier** [comment]
The NMLB-COG is ready for the release of this standard with the new values.

**Comment by cbarcl01** [comment]
Resolved as part of [PGPv5.5.0](https://github.com/cidgoh/pathogen-genomics-package/releases/tag/PGPv5.5.0)
