### ISSUE TITLE
NTR: new sample-collected-by sequencing centre_Kingston Health Sciences Centre

### ISSUE THREAD

**Issue by GLTOhorsman** [cidgoh/CanCOGeN_Contextual_Data_Specification#2]
### Proposed Term Label

Kingston Health Sciences Centre

### Proposed Associated Field(s)

sample collected by

### Definition/Description

Kingston Health Sciences Centre is the amalgamation of Kingston General Hospital and Hotel Dieu in Kingston. It delivers health care services to more than 500,000 residents throughout southeastern Ontario. It conducts health care research and trains future health care professionals.

### Definition Source

https://en.wikipedia.org/wiki/Kingston_General_Hospital
https://en.wikipedia.org/wiki/List_of_hospitals_in_Canada

### Guidance

Use this term when indicating COVID-19 samples extracted and sequenced at Kingston Health Sciences Centre and submitted by the Ontario COVID-19 Genomic Network

### Additional Comments (not an annotation)

This is the second of of three requests put forward by the Ontario COVID-19 Genomic Network in coordination with the National Microbiology Laboratory to facilitate data sharing. It will require both a term in dataharmonizer, and an export tolerance such that this term is accepted in the "NML LIMS" export. Please consult with user https://github.com/GH-Emily for timing of release to align with the matching changes they require on the NML side.

The existing term "Queen's University / Kingston Health Sciences Centre" is considered distinct and used to connote samples generated between Queen's and KHSC in 2021. The new standalone term will refer to a separate arrangement with a distinct set of samples

### Optional - Contributor Attribution

https://orcid.org/0000-0002-8117-5050

**Comment by GH-Emily** [comment]
NMLB-COG is okay with a **beta release** of this standard, but is currently unable to intake data with these new values.

**Comment by KirstenPalmier** [comment]
The NMLB-COG is ready for the release of this standard with the new values.

**Comment by cbarcl01** [comment]
Resolved as part of [PGPv5.5.0](https://github.com/cidgoh/pathogen-genomics-package/releases/tag/PGPv5.5.0)
