### ISSUE TITLE
NTR: Add sequence-submitted-by term Ontario COVID-19 Genomic Network

### ISSUE THREAD

**Issue by GLTOhorsman** [cidgoh/CanCOGeN_Contextual_Data_Specification#3]
### Proposed Term Label

Ontario COVID-19 Genomic Network

### Proposed Associated Field(s)

sequence submitted by

### Definition/Description

The Ontario COVID-19 Genomic Network (OCGN), includes the labs at PHO, Sick Kids, Kingston General Hospital, Shared Labs and Hamilton Health Sciences. The sequence data is submitted to external collaborators via a combined repository for Ontario.

### Definition Source

https://www.publichealthontario.ca/en/Diseases-and-Conditions/Infectious-Diseases/Respiratory-Diseases/Novel-Coronavirus/Lab-Testing-Ontario/Whole-Genome-Sequencing

### Guidance

Use this term to refer to samples submitted from the Ontario COVID-19 Genomic Network (OCGN) portal in Ontario.

### Additional Comments (not an annotation)

This is the third of three requests put forward by the Ontario COVID-19 Genomic Network in coordination with the National Microbiology Laboratory to facilitate data sharing. It will require both a term in dataharmonizer, and an export tolerance such that this term is accepted in the "NML LIMS" export. Please consult with user https://github.com/GH-Emily for timing of release to align with the matching changes they require on the NML side.

### Optional - Contributor Attribution

https://orcid.org/0000-0002-8117-5050

**Comment by GH-Emily** [comment]
NMLB-COG is okay with a **beta release** of this standard, but is currently unable to intake data with these new values.

**Comment by KirstenPalmier** [comment]
The NMLB-COG is ready for the release of this standard with the new values.

**Comment by cbarcl01** [comment]
Resolved as part of [PGPv5.5.0](https://github.com/cidgoh/pathogen-genomics-package/releases/tag/PGPv5.5.0)
